<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * @property $id
 * @property $url
 * @property $name
 * @property $request
 * @property $response
 * @property $sign
 *
 * Class ApiLog
 * @package App\Models
 */
class ApiLog extends Model
{
    protected $table = 'yl_api_logs';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::saving(function (ApiLog $log) {
            if (is_array($log->response)) {
                $log->response = json_encode($log->response);
            }

            if (is_array($log->request)) {
                $log->request = json_encode($log->request);
            }

        });

    }

    public static function logInfo($url ,$request, $response, $name = '', $sign = 0)
    {
        $model           = new static();
        $model->url  = $url;
        $model->request  = $request;
        $model->response = $response;
        $model->name     = $name;
        $model->sign     = $sign;
        $model->save();
    }
}
