<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class BaseResource extends JsonResource
{

    public static function collection($resource)
    {
        return parent::collection($resource)->additional(['code' => 1, 'message' => '', 'token' => app('our_auth')->getToken()]);
    }

    /**
     * Transform the resource into an array.
     *
     * @param \Illuminate\Http\Request $request
     * @return array
     */
    public function toArray($request)
    {
        return parent::toArray($request);
    }

    public function with($request)
    {
        return ['code' => 1, 'message' => '', 'token' => app('our_auth')->getToken()]; // TODO: Change the autogenerated stub
    }
}
